apiVersion: v1
kind: Service

metadata:
  name: cadence-performance-prod-service

spec:
  selector:
    app: cadence-performance

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: LoadBalancer